"""empty message

Revision ID: e57d6e0e014b
Revises: 
Create Date: 2019-10-01 10:21:49.338332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57d6e0e014b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills_users')
    op.add_column('items', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'])
    op.drop_column('items', 'is_checked')
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=False))
    op.drop_column('users', 'name')
    op.drop_column('users', 'hased_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hased_password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'email')
    op.add_column('items', sa.Column('is_checked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'user_id')
    op.create_table('bills_users',
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name='bills_users_bill_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='bills_users_item_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bills_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('bill_id', 'user_id', 'item_id', name='bills_users_pkey')
    )
    # ### end Alembic commands ###
